#!/bin/bash 

#----- Aliases -----#
alias ls='ls --color=auto'
alias ..='cd ..;pwd'
alias v=vim
alias c='clear'
alias tree='tree --dirsfirst -F'
alias mkdir='mkdir -p -v'

alias ls='ls --sort=extension --color=auto'
alias ll='ls -lh'
alias lal='ls -alh'
alias la='ls -A'
alias pms='sudo pm-suspend'
alias psg='ps -A | grep'
alias smi='sudo make install'
alias l='ls -CF'
alias mkd=mkdir

# Git Commands
# Add and Commit are used as functions
alias gpo='git push origin master'
alias gp='git pull'
alias gs='git status'
alias gd='git diff'
alias gr='git reflog'
alias glf='git ls-files'

# This one is to take care of make
# Give me a nice, distinguishable make output
alias make='clear && make'
alias m='make'

# Quickly load bashrc
alias gogo='source ~/.bashrc'

# Cool colors for man pages
alias man="TERMINFO=~/.terminfo TERM=mostlike LESS=C PAGER=less man"

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


